#!/usr/bin/env bash

hbase shell<<EOF
create 'students', 'name', 'age', 'iPadID'
create 'iPads', 'purchaseYear'
create 'teacher', 'name', 'subject'
create 'schools', 'name', 'type'
create 'rooms', 'name', 'school'
create 'roomBooking', 'name', 'bookedBy'
put 'students','pe120102', 'name: Peter', 'age: 12', 'iPadID: '
put 'students','la030202', 'name: Lars', 'age: 12', 'iPadID=> aaa'
put 'students','ja120901', 'name: Jannik', 'age: 13','iPadID=> ccc'
put 'students','sa101299', 'name: Sabine', 'age: 25','iPadID: '
put 'iPads','aaa', 'purchaseYear: 2022', ''
put 'iPads','bbb', 'purchaseYear: 2022', ''
put 'iPads','ccc', 'purchaseYear: 2022', ''
put 'iPads','ddd', 'purchaseYear: 2022',''
put 'teacher','mue', 'name:Mueller', 'subject: Englisch'
put 'teacher','bec', 'name:Becker', 'subject: Mathe'
put 'teacher','kle', 'name:Klein', 'subject: Sport'
put 'teacher','gro', 'name:Gross', 'subject: Deutsch'
put 'schools','msa1', 'name:Schule 1', 'subject: Gesamt'
put 'schools','msa2', 'name:Schule 2', 'subject: Gesamt'
put 'schools','msa3', 'name:Schule 3', 'subject: Gesamt'
put 'schools','abi1', 'name:Schule 4', 'subject: Abitur'
put 'rooms','room1', 'name:S1C2', 'school: msa1'
put 'rooms','room2', 'name:S1C1', 'school: msa1'
put 'rooms','room3', 'name:S3L2', 'school: msa3'
put 'rooms','room4', 'name:S4S2', 'school: abi1'
put 'roomBooking','b1', 'name:S4S2', 'bookedBy: gro'
put 'roomBooking','b2', 'name:S3L2', 'bookedBy: mue'
put 'roomBooking','b3', 'name:S4S2', 'bookedBy: kle'
put 'roomBooking','b4', 'name:S4S2', 'bookedBy: kle'
scan 'students'
scan 'iPads'
scan 'teacher'
scan 'schools'
scan 'rooms'
scan 'roomBooking'
deleteall 'students','la030202'
scan 'students'
EOF
